-- Orders
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  status VARCHAR(30) NOT NULL,
  zone VARCHAR(16) NOT NULL,
  instructions_accepted BOOLEAN NOT NULL,
  total_cents BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL
);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id UUID NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  unit_price_cents INT NOT NULL,
  qty INT NOT NULL,
  line_cents BIGINT NOT NULL,
  CONSTRAINT fk_order_items__order
    FOREIGN KEY (order_id) REFERENCES orders(id)
      ON DELETE CASCADE
);
